---
- name: system wide RoR
  hosts: server
vars:
    ruby: ruby-2.4.2
  tasks:
    - name: Update apt
      apt: update_cache=yes
      sudo: yes
    - name: Install base packages
      apt: pkg=$item state=latest
      sudo: yes
      with_items:
        - nodejs
        - curl
        - python-psycopg2
        - libpq-dev
    - name: install rvm
      shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm
    - name: install ruby
      shell: ~/.rvm/bin/rvm install --default {{ ruby }} creates=~/.rvm/rubies/{{ ruby }}
    - name: copy up .bashrc
      copy: dest=~/.bashrc
            src=files/bashrc
    - name: copy up .bash_profile
      copy: dest=~/.bash_profile
            src=files/bash_profile
...
